package engine

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/aystro/apod/internal/models"
)

func buildTraefikRule(domains []string) string {
	var hostRules []string
	for _, d := range domains {
		hostRules = append(hostRules, fmt.Sprintf("Host(`%s`)", d))
	}
	return strings.Join(hostRules, " || ")
}

func (e *Engine) AddDomain(ctx context.Context, siteDomain, newDomain string) error {
	// newDomain is rendered into Traefik Host(`...`) rules and must never be
	// able to break out of the backtick (rule injection / routing hijack).
	if err := ValidateDomain(newDomain); err != nil {
		return err
	}

	if err := e.locks.Acquire(siteDomain, "updating domains"); err != nil {
		return err
	}
	defer e.locks.Release(siteDomain)

	site, err := e.db.GetSite(siteDomain)
	if err != nil {
		return fmt.Errorf("get site: %w", err)
	}
	if site == nil {
		return NotFound("site %q not found", siteDomain)
	}

	// Reject a domain already used by any site (its primary domain or an alias)
	// with a clear conflict instead of an opaque UNIQUE-constraint 500.
	if existing, _ := e.db.GetSiteByDomain(newDomain); existing != nil {
		return Conflict("domain %q is already in use by site %q", newDomain, existing.Domain)
	}

	if err := e.db.AddDomain(site.ID, newDomain, false); err != nil {
		return fmt.Errorf("add domain: %w", err)
	}

	// Materialize routing. Without this the alias existed only as a DB row —
	// the primary router (container labels / site TOML) never includes aliases,
	// so "add domain" reported success while Traefik routed nothing.
	if err := e.applyAliasRouting(site); err != nil {
		// Keep the DB consistent with what's actually routed.
		e.db.RemoveDomainForSite(site.ID, newDomain)
		return fmt.Errorf("apply alias routing: %w", err)
	}

	return nil
}

// aliasRoutingPath is the Traefik file-provider config holding a site's
// alias-domain router.
func aliasRoutingPath(siteDomain string) string {
	return filepath.Join(traefikDynamicDir, "aliases-"+siteDomain+".toml")
}

// applyAliasRouting rewrites the file-provider router that serves a site's
// alias domains, reusing the site's existing Traefik service: the docker
// provider defines it (via container labels) for native sites, the site's
// dynamic TOML defines it for compose sites. With no aliases the file is
// removed.
func (e *Engine) applyAliasRouting(site *models.Site) error {
	domains, err := e.db.ListDomains(site.ID)
	if err != nil {
		return fmt.Errorf("list domains: %w", err)
	}
	var aliases []string
	for _, d := range domains {
		if d != site.Domain {
			aliases = append(aliases, d)
		}
	}
	path := aliasRoutingPath(site.Domain)
	if len(aliases) == 0 {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove alias routing: %w", err)
		}
		return nil
	}

	routerName := strings.ReplaceAll(site.Domain, ".", "-")
	provider := "docker"
	if e.drivers != nil {
		if driver, derr := e.drivers.Load(site.Driver); derr == nil && driver.Type == "compose" {
			provider = "file"
		}
	}
	service := routerName + "@" + provider
	rule := buildTraefikRule(aliases)

	var b strings.Builder
	b.WriteString("# Auto-generated by apod — do not edit\n")
	fmt.Fprintf(&b, "[http.routers.%s-aliases]\n  rule = %q\n  service = %q\n  entrypoints = [\"websecure\"]\n",
		routerName, rule, service)
	fmt.Fprintf(&b, "  [http.routers.%s-aliases.tls]\n", routerName)
	if resolver := e.tls.CertResolver(); resolver != "" {
		fmt.Fprintf(&b, "    certResolver = %q\n", resolver)
	}
	fmt.Fprintf(&b, "\n[http.routers.%s-aliases-http]\n  rule = %q\n  service = %q\n  entrypoints = [\"web\"]\n",
		routerName, rule, service)

	if err := os.MkdirAll(traefikDynamicDir, 0755); err != nil {
		return fmt.Errorf("create traefik dynamic dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write alias routing: %w", err)
	}
	return nil
}

func (e *Engine) RemoveDomain(ctx context.Context, siteDomain, removeDomain string) error {
	if err := e.locks.Acquire(siteDomain, "updating domains"); err != nil {
		return err
	}
	defer e.locks.Release(siteDomain)

	if removeDomain == siteDomain {
		return fmt.Errorf("cannot remove primary domain %q", siteDomain)
	}

	site, err := e.db.GetSite(siteDomain)
	if err != nil {
		return fmt.Errorf("get site: %w", err)
	}
	// Scope the delete to this site so a caller can't remove another tenant's
	// alias by name (IDOR).
	if err := e.db.RemoveDomainForSite(site.ID, removeDomain); err != nil {
		return fmt.Errorf("remove domain: %w", err)
	}

	// Rebuild the alias router so the removed domain stops routing.
	if err := e.applyAliasRouting(site); err != nil {
		return fmt.Errorf("apply alias routing: %w", err)
	}

	return nil
}

func (e *Engine) ListDomains(ctx context.Context, siteDomain string) ([]string, error) {
	site, err := e.db.GetSite(siteDomain)
	if err != nil {
		return nil, fmt.Errorf("get site: %w", err)
	}

	return e.db.ListDomains(site.ID)
}
