package engine

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// traefikDynamicDir is the host directory bind-mounted into Traefik as its file
// provider directory (/etc/traefik/dynamic in the container).
const traefikDynamicDir = "/etc/apod/traefik/dynamic"

// ipRuleRouterName mirrors the router name used in TraefikLabels.
func ipRuleRouterName(domain string) string {
	return strings.ReplaceAll(domain, ".", "-")
}

func ipAllowMiddlewareName(domain string) string {
	return ipRuleRouterName(domain) + "-ipallow"
}

// buildIPAllowListTOML renders a Traefik v2 file-provider middleware that
// restricts a router to the given source ranges. When allowIPs is empty it
// allows all traffic (so a site with no allow rules is never locked out). The
// returned config is deterministic (sorted by caller) and safe: values come
// from validated IP/CIDR strings.
func buildIPAllowListTOML(domain string, allowIPs []string) string {
	mw := ipAllowMiddlewareName(domain)
	ranges := allowIPs
	if len(ranges) == 0 {
		ranges = []string{"0.0.0.0/0", "::/0"}
	}
	quoted := make([]string, len(ranges))
	for i, r := range ranges {
		quoted[i] = fmt.Sprintf("%q", r)
	}
	return fmt.Sprintf("# Auto-generated by apod — do not edit\n[http.middlewares.%s.ipWhiteList]\n  sourceRange = [%s]\n",
		mw, strings.Join(quoted, ", "))
}

// ApplyIPRules materializes a site's allowlist into a Traefik dynamic-config
// middleware file. The middleware is attached to the site's router only when
// IP-rule enforcement is enabled (see TraefikLabels); the file is always
// written so the referenced middleware never dangles.
func (e *Engine) ApplyIPRules(domain string) error {
	rules, err := e.db.ListIPRules(domain)
	if err != nil {
		return err
	}
	var allow []string
	for _, r := range rules {
		if r.Action == "allow" {
			allow = append(allow, r.IP)
		}
	}

	if err := os.MkdirAll(traefikDynamicDir, 0755); err != nil {
		return fmt.Errorf("create traefik dynamic dir: %w", err)
	}
	path := filepath.Join(traefikDynamicDir, ipAllowMiddlewareName(domain)+".toml")
	content := buildIPAllowListTOML(domain, allow)
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("write ip allowlist: %w", err)
	}
	return nil
}

// ipRulesEnforced reports whether the per-site allowlist middleware should be
// attached to routers. Disabled by default: attaching a middleware changes live
// routing and must be smoke-tested against the deployment's Traefik first.
// Enable with APOD_ENFORCE_IP_RULES=1.
func ipRulesEnforced() bool {
	v := strings.ToLower(strings.TrimSpace(os.Getenv("APOD_ENFORCE_IP_RULES")))
	return v == "1" || v == "true" || v == "yes"
}
