package db

import "fmt"

var migrations = []string{
	`CREATE TABLE IF NOT EXISTS sites (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		domain TEXT NOT NULL UNIQUE,
		driver TEXT NOT NULL,
		status TEXT NOT NULL DEFAULT 'creating',
		ram TEXT NOT NULL DEFAULT '256M',
		cpu TEXT NOT NULL DEFAULT '1',
		env TEXT NOT NULL DEFAULT '{}',
		repo TEXT NOT NULL DEFAULT '',
		branch TEXT NOT NULL DEFAULT 'main',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS domains (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		site_id INTEGER NOT NULL,
		domain TEXT NOT NULL UNIQUE,
		is_primary INTEGER NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
	)`,
	`CREATE TABLE IF NOT EXISTS operations (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		site_domain TEXT NOT NULL,
		action TEXT NOT NULL,
		details TEXT NOT NULL DEFAULT '',
		result TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS api_keys (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		key_hash TEXT NOT NULL UNIQUE,
		scope TEXT NOT NULL DEFAULT '*',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS backups (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		site_domain TEXT NOT NULL,
		storage_name TEXT NOT NULL DEFAULT 'local',
		path TEXT NOT NULL,
		size_bytes INTEGER NOT NULL DEFAULT 0,
		status TEXT NOT NULL DEFAULT 'completed',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS storage_configs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE,
		driver TEXT NOT NULL,
		config TEXT NOT NULL DEFAULT '{}',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS backup_schedules (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		site_domain TEXT NOT NULL,
		cron_expr TEXT NOT NULL,
		storage_name TEXT NOT NULL DEFAULT 'local',
		keep_count INTEGER NOT NULL DEFAULT 7,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS deployments (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		site_domain TEXT NOT NULL,
		commit_hash TEXT NOT NULL DEFAULT '',
		branch TEXT NOT NULL DEFAULT 'main',
		status TEXT NOT NULL DEFAULT 'pending',
		previous_image TEXT NOT NULL DEFAULT '',
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS webhooks (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		site_domain TEXT NOT NULL,
		token TEXT NOT NULL UNIQUE,
		active INTEGER NOT NULL DEFAULT 1,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS uptime_checks (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		site_domain TEXT NOT NULL UNIQUE,
		url TEXT NOT NULL,
		interval_seconds INTEGER NOT NULL DEFAULT 60,
		alert_webhook TEXT NOT NULL DEFAULT '',
		active INTEGER NOT NULL DEFAULT 1,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS uptime_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		site_domain TEXT NOT NULL,
		status_code INTEGER NOT NULL,
		response_ms INTEGER NOT NULL,
		is_up INTEGER NOT NULL DEFAULT 1,
		checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	)`,
}

func (d *DB) migrate() error {
	for i, m := range migrations {
		if _, err := d.conn.Exec(m); err != nil {
			return fmt.Errorf("migration %d: %w", i, err)
		}
	}
	return nil
}
